def setup_UI(self):
    self.name = QLabel("Name: ")
    self.namef = QLineEdit()
    self.namef.setPlaceholderText("Material")
    layouth = QHBoxLayout()
    layoutv = QVBoxLayout()
    layouth.addWidget(self.name)
    layouth.addWidget(self.namef)
    layoutv.addLayout(layouth)
    self.calc_label = QLabel("Berechnungs-Typ: ")
    self.calc_type = QComboBox()
    self.calc_type.setPlaceholderText("Typ")
    self.calc_type.addItem("Sellmeier", userData=1)
    self.calc_type.addItem("Fester Brechungsindex", userData=0)
    self.calc_type.addItem("Formel", userData=2)
    self.calc_type.addItem("Interpolation", userData=3)
    layouth = QHBoxLayout()
    layouth.addWidget(self.calc_label)
    layouth.addWidget(self.calc_type)
    layoutv.addLayout(layouth)
    index = QLabel("Brechungsindex: ")
    self.real = QLineEdit()
    self.real.setPlaceholderText("Reell")
    self.real.setEnabled(False)
    self.imaginary = QLineEdit()
    self.imaginary.setPlaceholderText("Imaginär")
    self.imaginary.setEnabled(False)
    layouth = QHBoxLayout()
    layouth.addWidget(index)
    layouth.addWidget(self.real)
    layouth.addWidget(self.imaginary)
    layoutv.addLayout(layouth)
    self.coefficient_label = QLabel("Sellmeier-Koeffizienten")
    self.coefficientA = QLineEdit()
    self.coefficientA.setEnabled(False)
    self.coefficientA.setPlaceholderText("A=0")
    self.coefficientB = QLineEdit()
    self.coefficientB.setEnabled(False)
    self.coefficientB.setPlaceholderText("B1, B2, ...")
    self.coefficientC = QLineEdit()
    self.coefficientC.setEnabled(False)
    self.coefficientC.setPlaceholderText("C1, C2, ...")
    layouth = QHBoxLayout()
    layouth.addWidget(self.coefficient_label)
    layouth.addWidget(self.coefficientA)
    layouth.addWidget(self.coefficientB)
    layouth.addWidget(self.coefficientC)
    layoutv.addLayout(layouth)
    self.formula_label = QLabel("Formel:")
    self.formula = QLineEdit()
    self.formula.setPlaceholderText("Für Wellenlänge: x")
    self.formula.setEnabled(False)
    layouth = QHBoxLayout()
    layouth.addWidget(self.formula_label)
    layouth.addWidget(self.formula)
    layoutv.addLayout(layouth)
    self.table_label = QLabel("Tabelle")
    self.table = QPlainTextEdit()
    self.table.setEnabled(False)
    layouth = QHBoxLayout()
    layouth.addWidget(self.table_label)
    layouth.addWidget(self.table)
    layoutv.addLayout(layouth)
    self.confirm = QPushButton("Bestätigen")
    layoutv.addWidget(self.confirm)
    self.setLayout(layoutv)
